"""
Deliverables router — list, create, get, download.

Deliverables are generated by the Writer agent. An analyst picks a type
(executive_summary, investment_memo, dd_report), the API creates a
deliverable record + a generate_deliverable job, and the worker does the rest.
"""

import logging
import re
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response

from packages.db.client import require_one, safe_get_list
from packages.db.job_queue import create_job

from ..dependencies import DB, AnalystAuth, ViewerAuth, require_scope_dep
from ..models.common import ApiResponse
from ..models.deliverable import (
    DeliverableCreateRequest,
    DeliverableResponse,
)
from ..services.plan_limits import check_analysis_limit

logger = logging.getLogger(__name__)

router = APIRouter()


@router.get("/", dependencies=[Depends(require_scope_dep("deliverables:read"))])
async def list_deliverables(workspace_id: str, auth: ViewerAuth, db: DB):
    """List all deliverables for a workspace."""
    require_one(
        db.table("workspaces")
        .select("id")
        .eq("id", workspace_id)
        .eq("organization_id", auth.organization_id)
        .execute(),
        "Workspace",
    )

    deliverables = safe_get_list(
        db.table("deliverables")
        .select("*")
        .eq("workspace_id", workspace_id)
        .eq("organization_id", auth.organization_id)
        .order("created_at", desc=True)
        .execute()
    )

    return ApiResponse(data=[DeliverableResponse(**d) for d in deliverables])


@router.post(
    "/",
    status_code=202,
    dependencies=[Depends(require_scope_dep("deliverables:write"))],
)
async def create_deliverable(
    workspace_id: str,
    body: DeliverableCreateRequest,
    auth: AnalystAuth,
    db: DB,
):
    """Create a deliverable and queue generation job."""
    require_one(
        db.table("workspaces")
        .select("id")
        .eq("id", workspace_id)
        .eq("organization_id", auth.organization_id)
        .execute(),
        "Workspace",
    )

    await check_analysis_limit(db, auth.organization_id)

    now = datetime.now(timezone.utc).isoformat()

    result = (
        db.table("deliverables")
        .insert(
            {
                "workspace_id": workspace_id,
                "organization_id": auth.organization_id,
                "generated_by": auth.user_id,
                "type": body.type.value,
                "name": body.name,
                "options": body.options or {},
                "status": "pending",
                "created_at": now,
            }
        )
        .execute()
    )

    deliverable = require_one(result, "Deliverable")

    job = await create_job(
        db,
        type="generate_deliverable",
        payload={
            "deliverable_id": deliverable["id"],
            "workspace_id": workspace_id,
            "organization_id": auth.organization_id,
            "type": body.type.value,
        },
        organization_id=auth.organization_id,
    )

    logger.info(
        f"Deliverable {deliverable['id']} created, job {job['id']} queued "
        f"(type={body.type.value}, workspace={workspace_id})"
    )

    return ApiResponse(
        data=DeliverableResponse(**deliverable),
        meta={"job_id": job["id"]},
    )


@router.get(
    "/{deliverable_id}",
    dependencies=[Depends(require_scope_dep("deliverables:read"))],
)
async def get_deliverable(
    workspace_id: str,
    deliverable_id: str,
    auth: ViewerAuth,
    db: DB,
):
    """Get a single deliverable with full details."""
    deliverable = require_one(
        db.table("deliverables")
        .select("*")
        .eq("id", deliverable_id)
        .eq("workspace_id", workspace_id)
        .eq("organization_id", auth.organization_id)
        .execute(),
        "Deliverable",
    )

    return ApiResponse(data=DeliverableResponse(**deliverable))


@router.get(
    "/{deliverable_id}/download",
    dependencies=[Depends(require_scope_dep("deliverables:read"))],
)
async def download_deliverable(
    workspace_id: str,
    deliverable_id: str,
    auth: ViewerAuth,
    db: DB,
):
    """Download a completed deliverable DOCX file."""
    deliverable = require_one(
        db.table("deliverables")
        .select("id, file_path, name, status, organization_id")
        .eq("id", deliverable_id)
        .eq("workspace_id", workspace_id)
        .eq("organization_id", auth.organization_id)
        .execute(),
        "Deliverable",
    )

    if deliverable["status"] != "completed":
        raise HTTPException(status_code=400, detail="Deliverable is not ready yet")

    file_path = deliverable.get("file_path")
    if not file_path:
        raise HTTPException(
            status_code=404, detail="No file available for this deliverable"
        )

    try:
        data = db.storage.from_("deliverables").download(file_path)
    except Exception:
        logger.exception("Failed to download deliverable %s", deliverable_id)
        raise HTTPException(status_code=500, detail="Failed to download file")

    # Sanitise le nom pour éviter l'injection dans Content-Disposition
    safe_name = re.sub(r"[^\w\s\-.]", "", deliverable["name"]).strip() or "deliverable"
    filename = f"{safe_name}.docx"

    return Response(
        content=data,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )
